"""agregar columnas speed y pitch a reels

Revision ID: 676cbd769452
Revises: b37de043e0fe
Create Date: 2025-12-11 15:41:28.824916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676cbd769452'
down_revision = 'b37de043e0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.alter_column('access_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('PUBLIC', 'PREMIUM', 'PRIVATE', name='avataraccesstype'),
               nullable=False)

    with op.batch_alter_table('reel_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pitch', sa.Integer(), nullable=True))

    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pitch', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_column('pitch')
        batch_op.drop_column('speed')

    with op.batch_alter_table('reel_requests', schema=None) as batch_op:
        batch_op.drop_column('pitch')
        batch_op.drop_column('speed')
        batch_op.drop_column('voice_id')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.alter_column('access_type',
               existing_type=sa.Enum('PUBLIC', 'PREMIUM', 'PRIVATE', name='avataraccesstype'),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
