"""add user owner flag and avatar access columns

Revision ID: b37de043e0fe
Revises: d711cbd8cdd5
Create Date: 2025-11-05 10:45:47.387094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37de043e0fe'
down_revision = 'd711cbd8cdd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_type', sa.Enum('public', 'premium', 'private', name='avataraccesstype'), nullable=False, server_default='private'))
        batch_op.add_column(sa.Column('enabled_by_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('enabled_by_producer', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('enabled_by_subproducer', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_avatars_access_type'), ['access_type'], unique=False)

    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.alter_column('avatar_id', existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key('fk_reels_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_owner', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_owner')

    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reels_owner_id_users', type_='foreignkey')
        batch_op.alter_column('avatar_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avatars_access_type'))
        batch_op.drop_column('enabled_by_subproducer')
        batch_op.drop_column('enabled_by_producer')
        batch_op.drop_column('enabled_by_admin')
        batch_op.drop_column('access_type')

    # ### end Alembic commands ###
