"""add producer limits fields

Revision ID: d711cbd8cdd5
Revises: f4fa842447c8
Create Date: 2025-10-14 20:18:14.343124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd711cbd8cdd5'
down_revision = 'f4fa842447c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_subproducers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_affiliates', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_api_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producers', schema=None) as batch_op:
        batch_op.drop_column('monthly_api_limit')
        batch_op.drop_column('max_affiliates')
        batch_op.drop_column('max_subproducers')

    # ### end Alembic commands ###
